name: Python Code Quality Check

on:
  push:
    branches:
    - dev
  workflow_dispatch:
  
jobs:
  quality_check:
    name: Quality Check
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install pylint
      run: pip3 install pylint
